[tools]
aws-cli = { version = "latest", symlink_bins = "true" }
aws-sam = { version = "latest", symlink_bins = "true" }
"gem:jekyll" = "latest"
ruby = "latest"

[tasks.server]
alias = "dev"
run = "jekyll serve"

[tasks."build:site"]
run = "jekyll build"

[tasks."build:sam"]
run = "sam build"

[tasks.build]
depends = ["build:sam", "build:site"]

[tasks."deploy:infrastructure"]
depends = ["build:sam"]
run = "sam deploy"

[tasks.deploy]
depends = ["deploy:site", "deploy:infrastructure"]

[tasks."clean:site"]
run = "jekyll clean"
