#!/usr/bin/env bash

#MISE depends = ["build:site"]

set -euo pipefail

stack_name=$(perl -ne '/stack_name\s*=\s*"(.+?)"/ && print "$1\n"' < samconfig.toml | head -n 1)
region=$(perl -ne '/region\s*=\s*"(.+?)"/ && print "$1\n"' < samconfig.toml | head -n 1)

bucket_name=$(aws cloudformation describe-stacks \
  --region "$region" \
  --stack-name "$stack_name" \
  --query "Stacks[0].Outputs[?OutputKey=='BucketName'].OutputValue" \
  --output text)

distribution_id=$(aws cloudformation describe-stacks \
  --region "$region" \
  --stack-name "$stack_name" \
  --query "Stacks[0].Outputs[?OutputKey=='DistributionId'].OutputValue" \
  --output text)

echo "Syncing _site/ to s3://$bucket_name/"

aws s3 sync \
  --exclude '.DS_Store' \
  --exclude '*/.DS_Store' \
  --exclude '*.jpg' \
  --exclude '*.png' \
  _site/ "s3://$bucket_name/"

aws s3 sync \
  --size-only \
  --exclude '*' \
  --include '*.jpg' \
  --include '*.png' \
  _site/ "s3://$bucket_name/"

echo "Invalidating CloudFront distribution $distribution_id"

aws cloudfront create-invalidation \
  --distribution-id "$distribution_id" \
  --paths '/*' \
  --output text
